stages:
  - release
  - deploy

variables:
  CHART_VERSION: 0.1.1

release-helm-chart:
  stage: release
  image: alpine/helm:3.10.0
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_USER}:${NEXUS_PASS} ${NEXUS_URL}/repository/sausage-store-helm-marat-gumerov-06/ --upload-file sausage-store-${CHART_VERSION}.tgz
  only:
    changes:
      - sausage-store-chart/**/*

install-helm-chart:
  stage: deploy
  image: argoproj/argocd:v2.3.3
  script:
    - argocd app sync sausage-store-m-gumerov --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER
