replicas: 3
rollingUpdate:
  maxUnavaliable: "80%"
  maxSurge: "20%"

image:
  repository: gitlab.praktikum-services.ru:5050/m.gumerov/sausage-store/sausage-backend
  tag: c0853c04c952f8ea66fbaadc40e9f953fe0cd15c

resources:
  minAllowed:
    cpu: 0m
    memory: 0Mi
  maxAllowed:
    cpu: 1
    memory: 500Mi