---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-store-configmap
data:
  sausage-store.conf: |
    server {

      listen {{ .Values.global.frontend.port.external }};

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:{{ .Values.global.backend.port.external }};
      }
    }