---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: sausage-store-m-gumerov
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: sausage-store-m-gumerov
    env: {{ .Values.global.environment }}
spec:
  revisionHistoryLimit: 15
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: sausage-store-m-gumerov
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: sausage-store-m-gumerov
    spec:
      containers:
        - image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.global.frontend.port.internal }}
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-conf
        configMap:
          name: sausage-store-configmap
      imagePullSecrets:
        - name: docker-config-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}