backend-report:
  image:
    repository: gitlab.praktikum-services.ru:5050/m.gumerov/sausage-store/sausage-backend-report
    tag: latest
  env:
    - name: SERVER_PORT
      value: "8088"
    - name: SPRING_CLOUD_VAULT_HOST
      value: 51.250.85.231
  vault:
    secret:
      name: vault
      key: vault_token

hpa:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    cpuUtilization: 75