- name: Install OpenJDK-16
  apt:
    name: openjdk-16-jdk

- name: Add service user
  user:
    name: "{{ backend_service_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create service directory
  shell: |
    mkdir -m 0755 -p {{ backend_lib_directory }}
    mkdir -m 0755 -p {{ backend_report_directory }}
    sudo chown -R {{ backend_service_user }} {{ backend_service_directory }}

- name: Donwload backend artifact from Nexus
  maven_artifact:
    dest: "{{ backend_lib_directory }}/sausage-store.jar"
    repository_url: "{{ nexus_url }}/repository/sausage-store-gumerov-marat-backend/"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "{{ backend_maven_version }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_pass }}"
    owner: "{{ backend_service_user }}"

- name: Create backend systemd-unit file from template
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start backend service
  service:
    name: sausage-store-backend
    state: started