---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: sausage-store-m-gumerov
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: sausage-store-m-gumerov-m-gumerov
    env: {{ .Values.global.environment }}
spec:
  revisionHistoryLimit: 15
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: sausage-store-m-gumerov
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: sausage-store-m-gumerov
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: {{ .Values.global.backend.port.internal | quote }}
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.global.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.vault.secret.name }}
                  key: {{ .Values.global.vault.secret.key }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.global.backend.port.internal }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.global.backend.port.internal }}
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
