---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: sausage-store-m-gumerov
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: sausage-store-m-gumerov
    env: {{ .Values.global.environment }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        {{- with .Values.resources }}
        minAllowed:
          cpu: {{ .minAllowed.cpu }}
          memory: {{ .minAllowed.memory }}
        maxAllowed:
          cpu: {{ .maxAllowed.cpu }}
          memory: {{ .maxAllowed.memory }}
        {{- end }}
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits