---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.name }}-ingress
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.name }}-ingress-{{ .Chart.Version }}"
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: sausage-store
    env: {{ .Values.environment }}
spec:
  ingressClassName: {{ .Chart.ingress.className }}
  tls:
    - hosts:
        - {{ .Chart.ingress.host }}
  rules:
    - host: {{ .Chart.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8088