---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app: vault
data:
  vault_token: dmF1bHRyb290
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJtLmd1bWVyb3YiLCJwYXNzd29yZCI6IlZeNXgzY05bIiwiYXV0aCI6ImJTNW5kVzFsY205Mk9sWmVOWGd6WTA1YiJ9fX0=
type: kubernetes.io/dockerconfigjson