apiVersion: v1
kind: Service
metadata:
   name: backend-report
   labels:
     app: backend-report
spec:
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: backend-report